# Generated by scripts/brew-formula.sh on release — do not hand-edit.
class Railbase < Formula
  desc "Single-file enterprise backend with auto-CRUD, auth, admin and realtime"
  homepage "https://railbase.app"
  version "0.18.80"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://railbase.app/dl/railbase_darwin_arm64"
      sha256 "0ad3b844f6db403cc4bae5342429e32f7b5469d6f30ccbbac8a7bd8c9d774ad3"
    end
    on_intel do
      url "https://railbase.app/dl/railbase_darwin_amd64"
      sha256 "e65c3a46227420faaa7f44f19c7d1d3ed45fccc403d8d3bd7c1b9693337f47bf"
    end
  end

  on_linux do
    on_arm do
      url "https://railbase.app/dl/railbase_linux_arm64"
      sha256 "6538f491130d5922b8623df6fafa07db8a5e856c1fcecb33e30e98b345af9341"
    end
    on_intel do
      url "https://railbase.app/dl/railbase_linux_amd64"
      sha256 "412262e0aa32360c0dea1e50cc232a03a95dbac608a1621bcecbaae77b12d19e"
    end
  end

  def install
    bin.install Dir["railbase_*"].first => "railbase"
  end

  test do
    assert_match "railbase", shell_output("#{bin}/railbase --version")
  end
end
