# Generated by scripts/brew-formula.sh on release — do not hand-edit.
class Railbase < Formula
  desc "Single-file enterprise backend with auto-CRUD, auth, admin and realtime"
  homepage "https://railbase.app"
  version "0.18.38"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://railbase.app/dl/railbase_darwin_arm64"
      sha256 "13fdafa3f5e96053b053389d8e61e1a968b2f747deca20a4a945a825439fa34d"
    end
    on_intel do
      url "https://railbase.app/dl/railbase_darwin_amd64"
      sha256 "013637573837c3eb30bd12afc9edf8dd89ba39befe1ce171bf5df826482d427d"
    end
  end

  on_linux do
    on_arm do
      url "https://railbase.app/dl/railbase_linux_arm64"
      sha256 "fa2434fafa9cef1ada1a346359616b5479f34d477efb4484c105caa16fbab5f8"
    end
    on_intel do
      url "https://railbase.app/dl/railbase_linux_amd64"
      sha256 "9ecba7f3eaf2afc6db98e8765f5095ef6c0372a92f59f2922e02b2cedea6591d"
    end
  end

  def install
    bin.install Dir["railbase_*"].first => "railbase"
  end

  test do
    assert_match "railbase", shell_output("#{bin}/railbase --version")
  end
end
