# Generated by scripts/brew-formula.sh on release — do not hand-edit.
class Railbase < Formula
  desc "Single-file enterprise backend with auto-CRUD, auth, admin and realtime"
  homepage "https://railbase.app"
  version "0.18.75"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://railbase.app/dl/railbase_darwin_arm64"
      sha256 "20a11dc5c1e140cc3f985fece6a039cbda67341af6b2ed2919e13b6a7f879e6d"
    end
    on_intel do
      url "https://railbase.app/dl/railbase_darwin_amd64"
      sha256 "51b3f39d5b66681baa6a6df23d45134a95b41d5c3c7aad18a515f086a0820ced"
    end
  end

  on_linux do
    on_arm do
      url "https://railbase.app/dl/railbase_linux_arm64"
      sha256 "822c1363e7ef4df8b2c69b65598a45e47770b1b67338abb97a79e7f20977fac8"
    end
    on_intel do
      url "https://railbase.app/dl/railbase_linux_amd64"
      sha256 "681ad971708e12bdbaa10216f0227cf12302e5b9feaccf2657d897f48e8ab270"
    end
  end

  def install
    bin.install Dir["railbase_*"].first => "railbase"
  end

  test do
    assert_match "railbase", shell_output("#{bin}/railbase --version")
  end
end
